pipeline {
  agent any

  environment {
    AWS_REGION = "us-east-1"
    ACCOUNT_ID = "826828992763"
    ECR = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
    CLUSTER = "deployecho"
    NAMESPACE = "dev"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Get Git SHA') {
      steps {
        script {
          GIT_SHA = sh(
            script: "git rev-parse --short HEAD",
            returnStdout: true
          ).trim()
          env.TAG = "dev-${GIT_SHA}"
        }
      }
    }

    stage('Login to ECR') {
      steps {
        withCredentials([[
          $class: 'AmazonWebServicesCredentialsBinding',
          credentialsId: 'aws-creds',
          accessKeyVariable: 'AWS_ACCESS_KEY_ID',
          secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
        ]]) {
        sh '''
        set -e
        aws --version
        aws sts get-caller-identity

        aws ecr get-login-password --region us-east-1 | \
          docker login --username AWS --password-stdin \
          826828992763.dkr.ecr.us-east-1.amazonaws.com
      '''
        }
      }
    }


    stage('Build & Push Backend') {
      steps {
        sh """
        docker buildx build --platform linux/amd64 \
          -t ${ECR}/deployecho-backend:${TAG} \
          -f app/backend/Dockerfile app/backend \
          --push
        """
      }
    }

    stage('Build & Push Frontend') {
      steps {
        sh """
        docker buildx build --platform linux/amd64 \
          -t ${ECR}/deployecho-frontend:${TAG} \
          -f app/frontend/Dockerfile app/frontend \
          --push
        """
      }
    }

    stage('Deploy to EKS') {
      steps {
        withCredentials([[
          $class: 'AmazonWebServicesCredentialsBinding',
          credentialsId: 'aws-creds',
          accessKeyVariable: 'AWS_ACCESS_KEY_ID',
          secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
        ]]) {
          sh '''
            set -e
            aws sts get-caller-identity

            aws eks update-kubeconfig --region us-east-1 --name deployecho

            kubectl get ns
            kubectl apply -n dev -f k8s/
            kubectl rollout status -n dev deploy/deployecho-backend --timeout=180s
            kubectl rollout status -n dev deploy/deployecho-frontend --timeout=180s
          '''
        }
      }
    }
  }
}
